import type { Metadata } from 'next';
import './styles/globals.css';
import { Providers } from './providers';
import AuthContext from '@/context/auth-context';

export const metadata: Metadata = {
    title: 'Task Manager App',
    description: 'Generated by RL',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className='min-h-full flex flex-col'>
                <Providers>
                    <AuthContext>{children}</AuthContext>
                </Providers>
            </body>
        </html>
    );
}
